/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to edit this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_DragDrop;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.HangHangKhong;
import model.QuanLyChung;

/**
 *
 * @author Admin
 */
public class HangHangKhongFrameForm extends javax.swing.JFrame {

    private QuanLyChung qlc;
    private JTable table;
    private DefaultTableModel model;

    /**
     * Creates new form HangHangKhongFrameForm
     */
    public HangHangKhongFrameForm(QuanLyChung qlc) {
        this.qlc = qlc;
        setTitle("Quản lý hãng hàng không");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadData();
    }

    private void loadData() {
        model.setRowCount(0);
        for (HangHangKhong hhk : qlc.getDanhSachHang()) {
            model.addRow(new Object[]{
                hhk.getMaHang(),
                hhk.getTenHang(),
                hhk.getDanhSachMayBay().size()
            });
        }
    }

    private void themHang() {
        String ma = JOptionPane.showInputDialog("Mã hãng:");
        String ten = JOptionPane.showInputDialog("Tên hãng:");
        HangHangKhong hhk = new HangHangKhong(ma, ten);
        qlc.themHang(hhk);
        loadData();
    }

    private void xoaHang() {
        int row = table.getSelectedRow();
        if (row >= 0) {
            String ma = (String) model.getValueAt(row, 0);
            qlc.getDanhSachHang().removeIf(h -> h.getMaHang().equals(ma));
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý hãng hàng không");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hãng", "Tên hãng", "Số lượng máy bay"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);

        btnThem.setText("Thêm");
        jPanel1.add(btnThem);

        btnXoa.setText("Xóa");
        jPanel1.add(btnXoa);

        btnGhi.setText("Ghi file");
        jPanel1.add(btnGhi);

        btnDoc.setText("Đọc file");
        jPanel1.add(btnDoc);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        QuanLyChung qlc = new QuanLyChung();
        java.awt.EventQueue.invokeLater(() -> {
            new HangHangKhongFrameForm(qlc).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
