/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_DragDrop;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.QuanLyChung;
import model.TaiKhoan;

/**
 *
 * @author Admin
 */
public class TaiKhoanFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form TaiKhoanFrameForm
     */
    private QuanLyChung qlc;
    private DefaultTableModel model;

    public TaiKhoanFrameForm(QuanLyChung qlc) {
        this.qlc = qlc;
        setTitle("Quản lý tài khoản");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadData();
    }

    private void loadData() {
        model.setRowCount(0);
        for (TaiKhoan tk : qlc.getDanhSachTaiKhoan()) {
            model.addRow(new Object[]{
                tk.getTenDangNhap(),
                tk.getLoaiTaiKhoan()
            });
        }
    }

    private void themTaiKhoan() {
        String ten = JOptionPane.showInputDialog(this, "Tên đăng nhập:");
        if (ten == null || ten.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống!");
            return;
        }

        String mk = JOptionPane.showInputDialog(this, "Mật khẩu:");
        if (mk == null || mk.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
            return;
        }

        String loai = JOptionPane.showInputDialog(this, "Loại tài khoản (admin/user):");
        TaiKhoan.LoaiTaiKhoan loaiTK;

        if (loai == null) {
            return;
        }
        if (loai.equalsIgnoreCase("admin")) {
            loaiTK = TaiKhoan.LoaiTaiKhoan.ADMIN;
        } else if (loai.equalsIgnoreCase("user")) {
            loaiTK = TaiKhoan.LoaiTaiKhoan.USER;
        } else {
            JOptionPane.showMessageDialog(this, "Loại tài khoản không hợp lệ!");
            return;
        }

        TaiKhoan tk = new TaiKhoan(ten.trim(), mk.trim(), loaiTK);
        qlc.themTaiKhoan(tk);
        loadData();
        JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
    }

    private void xoaTaiKhoan() {
        int row = table.getSelectedRow();
        if (row >= 0) {
            String ten = (String) model.getValueAt(row, 0);
            boolean removed = qlc.getDanhSachTaiKhoan().removeIf(tk -> tk.getTenDangNhap().equals(ten));
            if (removed) {
                loadData();
                JOptionPane.showMessageDialog(this, "Đã xóa tài khoản: " + ten);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để xóa!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên đăng nhập", "Loại tài khoản"
            }
        ));
        JScrollPane1.setViewportView(table);

        getContentPane().add(JScrollPane1, java.awt.BorderLayout.CENTER);

        btnThem.setText("Thêm");
        jPanel1.add(btnThem);

        btnXoa.setText("Xóa");
        jPanel1.add(btnXoa);

        btnGhi.setText("Ghi file");
        jPanel1.add(btnGhi);

        btnDoc.setText("Đọc file");
        jPanel1.add(btnDoc);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyChung qlc = new QuanLyChung();
                new TaiKhoanFrameForm(qlc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
