/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_DragDrop;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.ChuyenBay;
import model.QuanLyChung;
import model.VeMayBay;

/**
 *
 * @author Admin
 */
public class VeFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form VẻameForm
     */
    private QuanLyChung qlc;
    private DefaultTableModel model;

    public VeFrameForm(QuanLyChung qlc) {
        this.qlc = qlc;
        setTitle("Quản lý vé máy bay");
        setSize(700, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadData();
    }

    private void loadData() {
        model.setRowCount(0);
        for (VeMayBay ve : qlc.getDanhSachVe()) {
            model.addRow(new Object[]{
                ve.getMaVe(),
                ve.getChuyenBay().getSoHieuChuyenBay(),
                ve.getHangVe(),
                ve.getGiaVe()
            });
        }
    }

    private void themVe() {
        String maVe = JOptionPane.showInputDialog("Mã vé:");
        String maCB = JOptionPane.showInputDialog("Số hiệu chuyến bay:");
        ChuyenBay cb = qlc.timChuyenBay(maCB);

        if (cb == null) {
            JOptionPane.showMessageDialog(null, "Chuyến bay không tồn tại!");
            return;
        }

        String input = JOptionPane.showInputDialog("Hạng vé (phổ thông/thương gia):");
        VeMayBay.HangVe hangVe = null;

        if (input != null) {
            switch (input.trim().toLowerCase()) {
                case "phổ thông":
                    hangVe = VeMayBay.HangVe.PHO_THONG;
                    break;
                case "thương gia":
                    hangVe = VeMayBay.HangVe.THUONG_GIA;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Hạng vé không hợp lệ!");
                    return;
            }
            double giaVe = Double.parseDouble(JOptionPane.showInputDialog("Giá vé:"));

            VeMayBay ve = new VeMayBay(maVe, cb, hangVe, giaVe);
            qlc.themVe(ve);
            loadData();
        }
    }

    private void xoaVe() {
        int row = table.getSelectedRow();
        if (row >= 0) {
            String maVe = (String) model.getValueAt(row, 0);
            qlc.xoaVe(maVe);
            loadData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã vé", "Chuyến Bay", "Hạng vé", "Giá vé"
            }
        ));
        JScrollPane1.setViewportView(table);

        getContentPane().add(JScrollPane1, java.awt.BorderLayout.CENTER);

        btnThem.setText("Thêm");
        jPanel1.add(btnThem);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        btnGhi.setText("Ghi file");
        jPanel1.add(btnGhi);

        btnDoc.setText("Đọc file");
        jPanel1.add(btnDoc);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyChung qlc = new QuanLyChung();
                new VeFrameForm(qlc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
